stages:
  - name: test
    if: type = pull_request OR branch = master
jobs:
  include:
    - stage: test
      language: objective-c
      os: osx
      osx_image: xcode11.4
      before_install:
        - nvm install v12.14.1 --reinstall-packages-from=default
        - nvm alias default v12.14.1
        - nvm use v12.14.1
        - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.22.4
        - export PATH="$HOME/.yarn/bin:$PATH"
      install:
        - yarn
        - cd ios
        - pod install
      script:
        - yarn bundle-ios